name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

env:
  PROJECT_TYPE: KEXT

jobs:
  build:
    name: Kext Build
    runs-on: macos-latest
    env:
      JOB_TYPE: BUILD
    steps:
    - name: Checkout VoodooI2C
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 500
    - name: Checkout MacKernelSDK
      uses: actions/checkout@v4
      with:
        repository: acidanthera/MacKernelSDK
        path: MacKernelSDK
    - name: CI Bootstrap
      run: |
        src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/ocbuild/master/ci-bootstrap.sh) && eval "$src" || exit 1

    - name: VoodooInput Bootstrap
      run: |
        src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/VoodooInput/master/VoodooInput/Scripts/bootstrap.sh) && eval "$src" && mv VoodooInput Dependencies

    - name: Fetch tags
      run: git fetch --tags --recurse-submodules=no

    - name: Get Commit SHA
      id: vars
      run: |
        echo "sha_short=$(git rev-parse --short=8 ${{ github.sha }})" >> $GITHUB_OUTPUT

    - name: Build Release VoodooI2C
      run: xcodebuild -workspace VoodooI2C.xcworkspace -scheme VoodooI2C -derivedDataPath build -jobs 1 -configuration Release

    - uses: actions/upload-artifact@v4
      with:
        name: VoodooI2C-${{ steps.vars.outputs.sha_short }}
        path: build/Build/Products/Release/*.kext
